version: "3.9"
services:
  web:
    build: .
    container_name: library_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=development
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: library_db
    restart: always
    environment:
      POSTGRES_USER: tama
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: library
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
