version: "3.9"

services:
  web:
    build: ./backend
    container_name: library_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql+psycopg2://tama:12345678@db:5432/library

  frontend:
    build: ./frontend
    container_name: library_frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    container_name: library_db
    restart: always
    environment:
      POSTGRES_USER: tama
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: library
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
